package models

type UpdateResult struct {
	MatchedCount  int64       // The number of documents matched by the filter.
	ModifiedCount int64       // The number of documents modified by the operation.
	UpsertedCount int64       // The number of documents upserted by the operation.
	UpsertedID    interface{} // The _id field of the upserted document, or nil if no upsert was done.
}

type InsertOneResult struct {
	// The _id of the inserted document. A value generated by the driver will be of type primitive.ObjectID.
	InsertedID interface{}
}

type DeleteResult struct {
	DeletedCount int64 `bson:"n"` // The number of documents deleted.
}

type ErrorResponse struct {
	Status string
}

type FCMResponse struct {
	Status string
}