name: Docker Image CI

on:
  workflow_dispatch:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Push to Docker Hub
        uses: actions/checkout@v2
        shell: bash
        run: 
          docker-compose build
          docker-compose login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker-compose tag ${{ secrets.DOCKER_REPOSITORY }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest
          docker-compose push
