name: Docker Image CI

on:
  workflow_dispatch:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        shell: bash
        env:
          repository: ${{ secrets.DOCKER_REPOSITORY }}
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
        id: docker-build
        run: 
          docker-compose build --build-arg BUILDKIT_INLINE_CACHE=1
          docker-compose login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker-compose tag ${{ secrets.DOCKER_REPOSITORY }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest
          docker-compose push
